[package]
name = "thesaurust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
exitfailure = "0.5.0"
reqwest = { version = "0.11.21", features = ["json"] }
serde = "1.0.187"
serde_json = "1.0.106"
serde_derive = "1.0.187"
tokio = { version = "1.32.0", features = ["full"] }
mockito = "1.1.1"
ratatui = "0.23.0"
crossterm = "0.27.0"
anyhow = "1.0.75"
tui-input = "0.8.0"
serpapi-search-rust = "0.1.0"
dotenvy = "0.15.7"

[dev-dependencies]
pretty_assertions = "1.4.0"
